export const FETCHING_MESSAGES = 'FETCHING_MESSAGES';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_LOAD_ERROR = 'MESSAGES_LOAD_ERROR';
export const CREATING_MESSAGE = 'CREATING_MESSAGE';
export const MESSAGE_CREATION_ERROR = 'MESSAGE_CREATION_ERROR';
