//Constants for Messages
export const SEARCHING_MESSAGES = 'SEARCHING_MESSAGES';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_LOAD_ERROR = 'MESSAGES_LOAD_ERROR';
export const CREATING_MESSAGE = 'CREATING_MESSAGE';
export const MESSAGE_CREATION_ERROR = 'MESSAGE_CREATION_ERROR';
export const MESSAGE_CREATED = 'MESSAGE_CREATED';
export const MESSAGES_REQUEST_ABORT = 'MESSAGES_REQUEST_ABORT';

//Constants for Colors
export const SEARCHING_COLORS = 'SEARCHING_COLORS';
export const COLORS_LOADED = 'COLORS_LOADED';
export const COLORS_LOAD_ERROR = 'COLORS_LOAD_ERROR';
