//Constants for Messages
export const LISTING_MESSAGES = 'LISTING_MESSAGES';
export const SEARCHING_MESSAGES = 'SEARCHING_MESSAGES';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_LOAD_ERROR = 'MESSAGES_LOAD_ERROR';
export const CREATING_MESSAGE = 'CREATING_MESSAGE';
export const MESSAGE_CREATION_ERROR = 'MESSAGE_CREATION_ERROR';

//Constants for Colors
export const LISTING_COLORS = 'LISTING_COLORS';
export const COLORS_LOADED = 'COLORS_LOADED';
export const COLORS_LOAD_ERROR = 'COLORS_LOAD_ERROR';
